name: chess-lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - shiny
  - chess
  - pandas
  - plotly
  - pydantic
  - pytest
  - shinywidgets
  - anywidget
  - pip:
    - shinyswatch==0.9.0